# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            anoop
tagline:          
description:      'thoughts on code, learning and sometimes law'
url:              http://www.anoopjoshi.com
baseurl:          '/'
paginate:         5

author:
  name:           'Anoop Joshi'
  url:            https://twitter.com/anooply

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/legallybrown
